version: '3.3'
services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: bigfut/corpquiz-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./corpquiz/nginx:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html/
      - ./corpquiz/docs/:/usr/share/nginx/html/api/v1/docs/
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
          - ./certbot/conf:/etc/letsencrypt:rw
          - ./certbot/www:/var/www/certbot:rw
      # command: certonly --webroot --webroot-path=/var/www/certbot/ --email bigftt@gmail.com --agree-tos --no-eff-email -d corpquiz.zapto.org
      depends_on:
        - nginx

  frontend:
    container_name: frontend
    image: bigfut/corpquiz-frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  db_value: